replicaCount: 1

config:
  inCluster: true
  inClusterContextName: vps

extraArgs:
  - "-in-cluster"
  - "-in-cluster-context-name=vps"
  - "-plugins-dir=/headlamp/plugins"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: __CERT_MANAGER_CLUSTER_ISSUER__
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: __HEADLAMP_DOMAIN__
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - __HEADLAMP_DOMAIN__