FROM ghcr.io/cirruslabs/flutter:stable AS builder

WORKDIR /app

COPY . .

RUN flutter pub get

ARG APP_API_URL
RUN test -n "$APP_API_URL" && flutter build web --release --dart-define=APP_API_URL=${APP_API_URL}

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
