FROM ghcr.io/cirruslabs/flutter:stable AS builder

WORKDIR /app

COPY . .

RUN flutter pub get

ARG API_URL=http://localhost:5000
RUN flutter build web --release --dart-define=API_URL=${API_URL}

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
