apiVersion: v1
kind: Service
metadata:
  name: app-cliente
  namespace: braza-burger
spec:
  selector:
    app: app-cliente
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cliente
  namespace: braza-burger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cliente
  template:
    metadata:
      labels:
        app: app-cliente
    spec:
      containers:
        - name: app-cliente
          image: docker.io/seu-usuario/app-cliente:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
