apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: braza-burger-monitoring-ingress
  namespace: braza-burger
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __GRAFANA_DOMAIN__
      secretName: grafana-tls
    - hosts:
        - __PROMETHEUS_DOMAIN__
      secretName: prometheus-tls
  rules:
    - host: __GRAFANA_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-bridge
                port:
                  number: 80
    - host: __PROMETHEUS_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-bridge
                port:
                  number: 9090
