apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: braza-burger-ingress
  namespace: braza-burger
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __APP_DOMAIN__
      secretName: app-tls
    - hosts:
        - __API_DOMAIN__
      secretName: api-tls
    - hosts:
        - __EVOLUTION_DOMAIN__
      secretName: evolution-tls
    - hosts:
        - __GRAFANA_DOMAIN__
      secretName: grafana-tls
    - hosts:
        - __PROMETHEUS_DOMAIN__
      secretName: prometheus-tls
  rules:
    - host: __APP_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-cliente
                port:
                  number: 80
    - host: __API_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-manager
                port:
                  number: 5000
    - host: __EVOLUTION_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evolution-api
                port:
                  number: 8080
    - host: __GRAFANA_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-bridge
                port:
                  number: 80
    - host: __PROMETHEUS_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-bridge
                port:
                  number: 9090
