apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: braza-burger
resources:
  - namespace.yaml
  - clusterissuer.yaml
  - api-manager.yaml
  - api-manager-hpa.yaml
  - app-cliente.yaml
  - evolution.yaml
  - monitoring-bridge-services.yaml
  - ingress.yaml
